apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-bot
  namespace: ai-nutritionist
  labels:
    app: sms-bot
    service: bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sms-bot
  template:
    metadata:
      labels:
        app: sms-bot
        service: bot
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: ai-nutritionist-service-account
      containers:
      - name: sms-bot
        image: ai-nutritionist/sms-bot:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: ai-nutritionist-config
        - secretRef:
            name: ai-nutritionist-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: sms-bot
  namespace: ai-nutritionist
spec:
  selector:
    app: sms-bot
  ports:
  - port: 8080
    targetPort: 8080
