# src/services/knowledge/sample_data.py

"""
Sample recipe dataset for RAG pipeline prototyping.
Contains diverse recipes across cuisines, dietary preferences, and difficulty levels.
"""

from typing import Any, Dict, List

SAMPLE_RECIPES: List[Dict[str, Any]] = [
    {
        "recipe_id": "recipe_001",
        "name": "Mediterranean Quinoa Bowl",
        "description": "A vibrant, protein-packed bowl with quinoa, chickpeas, cucumber, tomatoes, and a tangy lemon tahini dressing. Perfect for meal prep.",
        "cuisine": "mediterranean",
        "meal_type": ["lunch", "dinner"],
        "dietary_labels": ["vegetarian", "vegan", "gluten-free"],
        "allergens": ["sesame"],  # tahini contains sesame
        "calories": 450,
        "protein_g": 15,
        "carbs_g": 62,
        "fat_g": 18,
        "fiber_g": 12,
        "prep_time_min": 15,
        "cook_time_min": 20,
        "total_time_min": 35,
        "servings": 4,
        "difficulty": "easy",
        "ingredients": [
            {"name": "quinoa", "amount": "1 cup", "category": "grains"},
            {"name": "chickpeas", "amount": "1 can (15 oz)", "category": "protein"},
            {"name": "cucumber", "amount": "1 large", "category": "vegetables"},
            {"name": "cherry tomatoes", "amount": "2 cups", "category": "vegetables"},
            {"name": "tahini", "amount": "3 tbsp", "category": "condiments"},
            {"name": "lemon juice", "amount": "2 tbsp", "category": "condiments"},
            {"name": "olive oil", "amount": "2 tbsp", "category": "oils"},
        ],
        "estimated_cost_usd": 12.0,
        "cost_tier": "budget",
        "rating": 4.7,
        "review_count": 342,
        "popularity_score": 0.89,
        "source_name": "AI Nutritionist Curated",
        "verified": True,
    },
    {
        "recipe_id": "recipe_002",
        "name": "Grilled Salmon with Asparagus",
        "description": "Perfectly grilled wild-caught salmon with roasted asparagus and a garlic herb butter. High in omega-3 fatty acids and protein.",
        "cuisine": "american",
        "meal_type": ["dinner"],
        "dietary_labels": ["pescatarian", "gluten-free", "keto", "low-carb"],
        "allergens": ["fish", "dairy"],
        "calories": 380,
        "protein_g": 42,
        "carbs_g": 8,
        "fat_g": 20,
        "fiber_g": 4,
        "prep_time_min": 10,
        "cook_time_min": 15,
        "total_time_min": 25,
        "servings": 2,
        "difficulty": "medium",
        "ingredients": [
            {"name": "salmon fillet", "amount": "2 (6 oz each)", "category": "protein"},
            {"name": "asparagus", "amount": "1 lb", "category": "vegetables"},
            {"name": "butter", "amount": "2 tbsp", "category": "dairy"},
            {"name": "garlic", "amount": "3 cloves", "category": "aromatics"},
            {"name": "lemon", "amount": "1", "category": "produce"},
            {"name": "olive oil", "amount": "1 tbsp", "category": "oils"},
        ],
        "estimated_cost_usd": 18.0,
        "cost_tier": "premium",
        "rating": 4.9,
        "review_count": 567,
        "popularity_score": 0.95,
        "source_name": "AI Nutritionist Curated",
        "verified": True,
    },
    {
        "recipe_id": "recipe_003",
        "name": "Vegetarian Black Bean Tacos",
        "description": "Quick and easy black bean tacos with avocado, salsa, and a squeeze of lime. Budget-friendly and packed with plant-based protein.",
        "cuisine": "mexican",
        "meal_type": ["lunch", "dinner"],
        "dietary_labels": ["vegetarian", "vegan-option"],
        "allergens": ["gluten"],  # tortillas contain gluten
        "calories": 320,
        "protein_g": 12,
        "carbs_g": 48,
        "fat_g": 10,
        "fiber_g": 14,
        "prep_time_min": 10,
        "cook_time_min": 10,
        "total_time_min": 20,
        "servings": 4,
        "difficulty": "easy",
        "ingredients": [
            {"name": "black beans", "amount": "2 cans (15 oz each)", "category": "protein"},
            {"name": "corn tortillas", "amount": "8", "category": "grains"},
            {"name": "avocado", "amount": "2", "category": "produce"},
            {"name": "salsa", "amount": "1 cup", "category": "condiments"},
            {"name": "lime", "amount": "2", "category": "produce"},
            {"name": "cilantro", "amount": "1/4 cup", "category": "herbs"},
            {"name": "cumin", "amount": "1 tsp", "category": "spices"},
        ],
        "estimated_cost_usd": 8.0,
        "cost_tier": "budget",
        "rating": 4.6,
        "review_count": 892,
        "popularity_score": 0.92,
        "source_name": "AI Nutritionist Curated",
        "verified": True,
    },
    {
        "recipe_id": "recipe_004",
        "name": "Chicken Tikka Masala",
        "description": "Authentic Indian curry with tender chicken pieces in a creamy tomato-based sauce. Rich in flavor and perfect with basmati rice or naan.",
        "cuisine": "indian",
        "meal_type": ["dinner"],
        "dietary_labels": ["gluten-free"],
        "allergens": ["dairy"],
        "calories": 520,
        "protein_g": 38,
        "carbs_g": 28,
        "fat_g": 28,
        "fiber_g": 6,
        "prep_time_min": 20,
        "cook_time_min": 40,
        "total_time_min": 60,
        "servings": 6,
        "difficulty": "medium",
        "ingredients": [
            {"name": "chicken breast", "amount": "2 lbs", "category": "protein"},
            {"name": "yogurt", "amount": "1 cup", "category": "dairy"},
            {"name": "heavy cream", "amount": "1 cup", "category": "dairy"},
            {"name": "tomato sauce", "amount": "2 cups", "category": "condiments"},
            {"name": "garam masala", "amount": "2 tbsp", "category": "spices"},
            {"name": "ginger", "amount": "1 inch", "category": "aromatics"},
            {"name": "garlic", "amount": "4 cloves", "category": "aromatics"},
            {"name": "onion", "amount": "1 large", "category": "vegetables"},
        ],
        "estimated_cost_usd": 15.0,
        "cost_tier": "moderate",
        "rating": 4.8,
        "review_count": 1243,
        "popularity_score": 0.97,
        "source_name": "AI Nutritionist Curated",
        "verified": True,
    },
    {
        "recipe_id": "recipe_005",
        "name": "Overnight Oats with Berries",
        "description": "No-cook breakfast packed with fiber, protein, and antioxidants. Prep 5 days worth in just 15 minutes for easy grab-and-go mornings.",
        "cuisine": "american",
        "meal_type": ["breakfast"],
        "dietary_labels": ["vegetarian", "vegan-option"],
        "allergens": ["dairy"],  # can be made dairy-free
        "calories": 280,
        "protein_g": 10,
        "carbs_g": 45,
        "fat_g": 8,
        "fiber_g": 8,
        "prep_time_min": 5,
        "cook_time_min": 0,
        "total_time_min": 5,  # plus overnight refrigeration
        "servings": 1,
        "difficulty": "easy",
        "ingredients": [
            {"name": "rolled oats", "amount": "1/2 cup", "category": "grains"},
            {"name": "milk", "amount": "3/4 cup", "category": "dairy"},
            {"name": "greek yogurt", "amount": "1/4 cup", "category": "dairy"},
            {"name": "mixed berries", "amount": "1/2 cup", "category": "fruit"},
            {"name": "honey", "amount": "1 tbsp", "category": "sweeteners"},
            {"name": "chia seeds", "amount": "1 tbsp", "category": "seeds"},
        ],
        "estimated_cost_usd": 3.0,
        "cost_tier": "budget",
        "rating": 4.5,
        "review_count": 678,
        "popularity_score": 0.85,
        "source_name": "AI Nutritionist Curated",
        "verified": True,
    },
    {
        "recipe_id": "recipe_006",
        "name": "Thai Green Curry with Tofu",
        "description": "Aromatic Thai curry with crispy tofu, vegetables, and coconut milk. Naturally vegan and full of bold flavors.",
        "cuisine": "thai",
        "meal_type": ["lunch", "dinner"],
        "dietary_labels": ["vegan", "gluten-free"],
        "allergens": [],
        "calories": 390,
        "protein_g": 16,
        "carbs_g": 35,
        "fat_g": 22,
        "fiber_g": 6,
        "prep_time_min": 15,
        "cook_time_min": 25,
        "total_time_min": 40,
        "servings": 4,
        "difficulty": "medium",
        "ingredients": [
            {"name": "firm tofu", "amount": "14 oz", "category": "protein"},
            {"name": "green curry paste", "amount": "3 tbsp", "category": "condiments"},
            {"name": "coconut milk", "amount": "1 can (14 oz)", "category": "dairy-alternative"},
            {"name": "bell peppers", "amount": "2", "category": "vegetables"},
            {"name": "bamboo shoots", "amount": "1 cup", "category": "vegetables"},
            {"name": "thai basil", "amount": "1/2 cup", "category": "herbs"},
            {"name": "fish sauce substitute", "amount": "2 tbsp", "category": "condiments"},
        ],
        "estimated_cost_usd": 11.0,
        "cost_tier": "budget",
        "rating": 4.7,
        "review_count": 534,
        "popularity_score": 0.88,
        "source_name": "AI Nutritionist Curated",
        "verified": True,
    },
    {
        "recipe_id": "recipe_007",
        "name": "Classic Italian Margherita Pizza",
        "description": "Authentic Neapolitan-style pizza with fresh mozzarella, tomato sauce, and basil. Simple ingredients, extraordinary taste.",
        "cuisine": "italian",
        "meal_type": ["lunch", "dinner"],
        "dietary_labels": ["vegetarian"],
        "allergens": ["gluten", "dairy"],
        "calories": 580,
        "protein_g": 24,
        "carbs_g": 68,
        "fat_g": 22,
        "fiber_g": 4,
        "prep_time_min": 30,
        "cook_time_min": 12,
        "total_time_min": 42,
        "servings": 2,
        "difficulty": "hard",
        "ingredients": [
            {"name": "pizza dough", "amount": "1 lb", "category": "grains"},
            {"name": "fresh mozzarella", "amount": "8 oz", "category": "dairy"},
            {"name": "san marzano tomatoes", "amount": "1 can (14 oz)", "category": "vegetables"},
            {"name": "fresh basil", "amount": "1/2 cup", "category": "herbs"},
            {"name": "olive oil", "amount": "3 tbsp", "category": "oils"},
            {"name": "garlic", "amount": "2 cloves", "category": "aromatics"},
        ],
        "estimated_cost_usd": 14.0,
        "cost_tier": "moderate",
        "rating": 4.9,
        "review_count": 1876,
        "popularity_score": 0.98,
        "source_name": "AI Nutritionist Curated",
        "verified": True,
    },
    {
        "recipe_id": "recipe_008",
        "name": "Korean Bibimbap Bowl",
        "description": "Colorful rice bowl topped with seasoned vegetables, gochujang sauce, and a fried egg. Balanced macros and incredible flavors.",
        "cuisine": "korean",
        "meal_type": ["lunch", "dinner"],
        "dietary_labels": ["gluten-free-option"],
        "allergens": ["egg", "soy"],
        "calories": 480,
        "protein_g": 20,
        "carbs_g": 72,
        "fat_g": 14,
        "fiber_g": 8,
        "prep_time_min": 20,
        "cook_time_min": 30,
        "total_time_min": 50,
        "servings": 4,
        "difficulty": "medium",
        "ingredients": [
            {"name": "white rice", "amount": "2 cups", "category": "grains"},
            {"name": "spinach", "amount": "2 cups", "category": "vegetables"},
            {"name": "carrots", "amount": "2", "category": "vegetables"},
            {"name": "mushrooms", "amount": "8 oz", "category": "vegetables"},
            {"name": "zucchini", "amount": "1", "category": "vegetables"},
            {"name": "eggs", "amount": "4", "category": "protein"},
            {"name": "gochujang", "amount": "3 tbsp", "category": "condiments"},
            {"name": "sesame oil", "amount": "2 tbsp", "category": "oils"},
        ],
        "estimated_cost_usd": 13.0,
        "cost_tier": "moderate",
        "rating": 4.8,
        "review_count": 723,
        "popularity_score": 0.91,
        "source_name": "AI Nutritionist Curated",
        "verified": True,
    },
    {
        "recipe_id": "recipe_009",
        "name": "High-Protein Smoothie Bowl",
        "description": "Thick, creamy smoothie bowl with 30g protein, topped with granola, nuts, and fresh fruit. Perfect post-workout meal.",
        "cuisine": "american",
        "meal_type": ["breakfast", "snack"],
        "dietary_labels": ["vegetarian", "gluten-free-option"],
        "allergens": ["dairy", "nuts"],
        "calories": 420,
        "protein_g": 30,
        "carbs_g": 48,
        "fat_g": 14,
        "fiber_g": 10,
        "prep_time_min": 10,
        "cook_time_min": 0,
        "total_time_min": 10,
        "servings": 1,
        "difficulty": "easy",
        "ingredients": [
            {"name": "protein powder", "amount": "1 scoop", "category": "protein"},
            {"name": "banana", "amount": "1 frozen", "category": "fruit"},
            {"name": "greek yogurt", "amount": "1 cup", "category": "dairy"},
            {"name": "almond milk", "amount": "1/2 cup", "category": "dairy-alternative"},
            {"name": "granola", "amount": "1/4 cup", "category": "grains"},
            {"name": "mixed nuts", "amount": "2 tbsp", "category": "nuts"},
            {"name": "berries", "amount": "1/2 cup", "category": "fruit"},
        ],
        "estimated_cost_usd": 5.0,
        "cost_tier": "budget",
        "rating": 4.6,
        "review_count": 412,
        "popularity_score": 0.83,
        "source_name": "AI Nutritionist Curated",
        "verified": True,
    },
    {
        "recipe_id": "recipe_010",
        "name": "Moroccan Chickpea Stew",
        "description": "Warming North African stew with chickpeas, sweet potatoes, and aromatic spices. Vegan, hearty, and budget-friendly.",
        "cuisine": "moroccan",
        "meal_type": ["lunch", "dinner"],
        "dietary_labels": ["vegan", "gluten-free"],
        "allergens": [],
        "calories": 360,
        "protein_g": 14,
        "carbs_g": 58,
        "fat_g": 8,
        "fiber_g": 16,
        "prep_time_min": 15,
        "cook_time_min": 35,
        "total_time_min": 50,
        "servings": 6,
        "difficulty": "easy",
        "ingredients": [
            {"name": "chickpeas", "amount": "2 cans (15 oz each)", "category": "protein"},
            {"name": "sweet potatoes", "amount": "2 large", "category": "vegetables"},
            {"name": "diced tomatoes", "amount": "1 can (28 oz)", "category": "vegetables"},
            {"name": "onion", "amount": "1 large", "category": "vegetables"},
            {"name": "cumin", "amount": "2 tsp", "category": "spices"},
            {"name": "cinnamon", "amount": "1 tsp", "category": "spices"},
            {"name": "vegetable broth", "amount": "2 cups", "category": "liquids"},
        ],
        "estimated_cost_usd": 10.0,
        "cost_tier": "budget",
        "rating": 4.7,
        "review_count": 589,
        "popularity_score": 0.87,
        "source_name": "AI Nutritionist Curated",
        "verified": True,
    },
]


def get_recipes_by_cuisine(cuisine: str) -> List[Dict[str, Any]]:
    """Filter recipes by cuisine type."""
    return [r for r in SAMPLE_RECIPES if r["cuisine"] == cuisine]


def get_recipes_by_dietary_label(label: str) -> List[Dict[str, Any]]:
    """Filter recipes by dietary label."""
    return [r for r in SAMPLE_RECIPES if label in r["dietary_labels"]]


def get_recipes_by_max_time(max_time_min: int) -> List[Dict[str, Any]]:
    """Filter recipes by maximum total time."""
    return [r for r in SAMPLE_RECIPES if r["total_time_min"] <= max_time_min]


def get_high_protein_recipes(min_protein_g: int = 20) -> List[Dict[str, Any]]:
    """Get recipes with high protein content."""
    return [r for r in SAMPLE_RECIPES if r["protein_g"] >= min_protein_g]


def get_budget_friendly_recipes(max_cost_usd: float = 10.0) -> List[Dict[str, Any]]:
    """Get budget-friendly recipes."""
    return [r for r in SAMPLE_RECIPES if r["estimated_cost_usd"] <= max_cost_usd]
