apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-coach-service
  namespace: ai-nutritionist-dev
spec:
  template:
    spec:
      containers:
      - name: ai-coach-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        env:
        - name: AI_MODEL_ENDPOINT
          value: "localhost:8080"  # Mock endpoint for development

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-service
  namespace: ai-nutritionist-dev
spec:
  template:
    spec:
      containers:
      - name: nutrition-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
