apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-nutritionist-dev

resources:
- ../../base

patchesStrategicMerge:
- patches/deployment-dev.yaml
- patches/configmap-dev.yaml

configMapGenerator:
- name: ai-nutritionist-config
  behavior: merge
  literals:
  - ENVIRONMENT=development
  - LOG_LEVEL=DEBUG
  - FEATURE_AI_OPTIMIZATION=false
  - CACHE_TTL=300

replicas:
- name: nutrition-service
  count: 1
- name: ai-coach-service
  count: 1
- name: messaging-service
  count: 1
- name: health-tracking-service
  count: 1
- name: payment-service
  count: 1
- name: web-app
  count: 1

images:
- name: ai-nutritionist/nutrition-service
  newTag: dev-latest
- name: ai-nutritionist/ai-coach-service
  newTag: dev-latest
- name: ai-nutritionist/messaging-service
  newTag: dev-latest
- name: ai-nutritionist/health-tracking-service
  newTag: dev-latest
- name: ai-nutritionist/payment-service
  newTag: dev-latest
- name: ai-nutritionist/web-app
  newTag: dev-latest

commonLabels:
  environment: development
  tier: dev

commonAnnotations:
  environment: development
