apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-coach-service
  namespace: ai-nutritionist
  labels:
    app: ai-coach-service
    service: ai-coach
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-coach-service
  template:
    metadata:
      labels:
        app: ai-coach-service
        service: ai-coach
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: ai-nutritionist-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: ai-coach-service
        image: ai-nutritionist/ai-coach-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: metrics
        env:
        - name: PORT
          value: "8080"
        - name: METRICS_PORT
          value: "8081"
        - name: AI_MODEL_ENDPOINT
          value: "bedrock.us-east-1.amazonaws.com"
        envFrom:
        - configMapRef:
            name: ai-nutritionist-config
        - secretRef:
            name: ai-nutritionist-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/cache
        - name: model-cache
          mountPath: /app/model-cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      - name: model-cache
        emptyDir:
          sizeLimit: 2Gi
      imagePullSecrets:
      - name: registry-secret
      nodeSelector:
        node-type: ai-workload
      tolerations:
      - key: "ai-workload"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: ai-coach-service
  namespace: ai-nutritionist
  labels:
    app: ai-coach-service
    service: ai-coach
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
spec:
  selector:
    app: ai-coach-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-coach-service-hpa
  namespace: ai-nutritionist
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-coach-service
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: ai_requests_per_second
      target:
        type: AverageValue
        averageValue: "50"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 200
        periodSeconds: 15
      - type: Pods
        value: 5
        periodSeconds: 15
      selectPolicy: Max
