apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-nutritionist-prod

resources:
- ../../base

patchesStrategicMerge:
- patches/deployment-prod.yaml
- patches/hpa-prod.yaml

configMapGenerator:
- name: ai-nutritionist-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=INFO
  - FEATURE_AI_OPTIMIZATION=true
  - FEATURE_ADVANCED_CACHING=true
  - CACHE_TTL=3600
  - MAX_CONNECTIONS=1000

replicas:
- name: nutrition-service
  count: 5
- name: ai-coach-service
  count: 3
- name: messaging-service
  count: 4
- name: health-tracking-service
  count: 2
- name: payment-service
  count: 3
- name: web-app
  count: 5

images:
- name: ai-nutritionist/nutrition-service
  newTag: v1.2.3
- name: ai-nutritionist/ai-coach-service
  newTag: v1.2.3
- name: ai-nutritionist/messaging-service
  newTag: v1.2.3
- name: ai-nutritionist/health-tracking-service
  newTag: v1.2.3
- name: ai-nutritionist/payment-service
  newTag: v1.2.3
- name: ai-nutritionist/web-app
  newTag: v1.2.3

commonLabels:
  environment: production
  tier: prod

commonAnnotations:
  environment: production
  monitoring: enabled
