apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ai-coach-service-vpa
  namespace: ai-nutritionist
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-coach-service
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: ai-coach-service
      minAllowed:
        cpu: 200m
        memory: 256Mi
      maxAllowed:
        cpu: 2000m
        memory: 2Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nutrition-service-vpa
  namespace: ai-nutritionist
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nutrition-service
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: nutrition-service
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 1000m
        memory: 1Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: messaging-service-vpa
  namespace: ai-nutritionist
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: messaging-service
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: messaging-service
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 800m
        memory: 512Mi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-nutritionist-quota
  namespace: ai-nutritionist
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    secrets: "10"
    configmaps: "10"
    count/deployments.apps: "15"
    count/statefulsets.apps: "5"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: ai-nutritionist-limits
  namespace: ai-nutritionist
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    min:
      cpu: 50m
      memory: 64Mi
    max:
      cpu: 2000m
      memory: 4Gi
  - type: Pod
    max:
      cpu: 4000m
      memory: 8Gi
  - type: PersistentVolumeClaim
    min:
      storage: 1Gi
    max:
      storage: 100Gi

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-coach-service-pdb
  namespace: ai-nutritionist
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-coach-service

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nutrition-service-pdb
  namespace: ai-nutritionist
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nutrition-service

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: messaging-service-pdb
  namespace: ai-nutritionist
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: messaging-service

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-app-pdb
  namespace: ai-nutritionist
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: web-app
